---
title: "ml-logistic-reg"
output: html_document
date: "2023-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#options(knitr.duplicate.label = "allow")
```

## Libraries
```{r library}
#install.packages("lme4")
#install.packages("lm.beta")
#install.packages("nlme")
#install.packages("lmerTest")
#install.packages("car")
#install.packages("MuMIn")
#install.packages("knitr")
#install.packages("rmarkdown")
#install.packages("devtools")
#library(devtools)
#install_github("regbook/regbook")
#library(regbook)
# Load package

library(rmarkdown)
library(knitr)

library(car)
library(lme4)
library(lm.beta)
library(nlme)
library(lmerTest)
library(MuMIn)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(regbook)



```
# Read Files

```{r data}
# read data
data <- read.csv(file="(binary)multilevel_regression_data_v5_not_normed.csv", header=TRUE, sep=",",stringsAsFactors=TRUE)
summary(data)
```

# Read Files

```{r test}
#contr.helmert(2)
#contr.sum(4)
#contrasts(data$condition) = contr.treatment(5)
#
#hsb2 = read.table('https://stats.idre.ucla.edu/stat/data/hsb2.csv', header=T, sep=",")
#hsb2$race.f = factor(hsb2$race, labels=c("Hispanic", "Asian", "African-Am", "Caucasian"))
#contrasts(hsb2$race.f) = contr.treatment(4)

#head(adsale)



```



# glmer 모델 

```{r model}
# run model
#model <- glmer(responserate ~ Gender
#               + Extroversion_score + Agreeableness_score + Conscientiousness_score + Neuroticism_score + Openness_score
#               + dayofweek +	weekend +	time + condition
#               + (1 | uid)
#               , data = data, family = 'binomial', nAGQ = 0 ,
#               contrasts = list(dayofweek = contr.sum, weekend = contr.sum, time = contr.sum, condition = contr.sum)
#               )
#model.matrix(model)

```


# setting reference 

```{r reference}
data$condition <-relevel(data$condition, ref = "Maximum Time Interval")
data$dayofweek <-relevel(data$dayofweek, ref = "mon")
data$weekend <-relevel(data$weekend, ref = "weekend")
data$time <-relevel(data$time, ref = "daytime")



```

# glmer 모델 만들기  

```{r re model}
# re-run model
model <- glmer(responserate ~ Gender
               + Extroversion_score + Agreeableness_score + Conscientiousness_score + Neuroticism_score + Openness_score
               + dayofweek +	time + condition # +	weekend
               + (1 | uid) #+ (1| condition) #수정
               , data = data, family = 'binomial', nAGQ = 1 ,
               contrasts = list(dayofweek = contr.sum, time = contr.sum) #, condition = contr.sum) #weekend = contr.sum, 
               )
# model.matrix(model)
summary(model)
```



# random effect 해석 

```{r random effect }
# https://bookdown.org/steve_midway/DAR/random-effects.html
coef(model)$uid

```

#  contrast - day of week 


```{r dummied }
contrasts(data$dayofweek)
```




#  contrast - time


```{r time }
contrasts(data$time)
```


## beta coefficient  


```{r betacoff }
#beta coefficient 
tab_model(model, transform = NULL, show.se = TRUE, show.ci = FALSE, show.stat = TRUE, show.obs = FALSE, show.r2 = FALSE, show.p = FALSE,
          show.re.var = FALSE, show.icc = FALSE, show.reflvl = FALSE)

```


## odds ratio  


```{r odds_ratio }
#odds
tab_model(model) #tab_model(model, string.est = TRUE) x

```

## contrast 

```{r contrast }
contrast <- attributes(model.matrix(model))$contrasts

```